version: "3.0"
services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      WA_BROWSER_WS_ENDPOINT: 'http://browser:3000'
      WA_DISABLE_SPINS: 'true'
